name: newshive
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.1
  flutter_launcher_icons: ^0.14.4
  image_picker: ^1.0.5
  http: ^1.1.0


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  image_path: "assets/images/icon.png"
  android: "launcher_icons"
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/